---
- name: Configure Redis
  lineinfile:
    path: "{{ config_filepath }}"
    regexp: "^{{ item.key }}[\\s\\t]+"
    line: "{{ item.key }} {{ item.value }}"
  when: item.value is not none
  loop_control:
    label: "{{ config_filepath }} {{ item.key }}={{ item.value }}"
  with_dict: "{{ redis['redis.conf'] }}"
  vars:
    config_filepath: "{{ redis.prefix.config }}/redis.conf"
  notify: Restart Redis
