---
- name: Install Redis
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: redis-server
  register: redis_sentinel_service_result

- when:
    - redis.replication.sentinel
    - ansible_distribution == 'Ubuntu'
  block:

    - name: Install Redis Sentinel
      apt:
        name: redis-sentinel

    - name: Stop Redis Sentinel
      when: redis_sentinel_service_result.changed
      service:
        name: redis-sentinel
        state: stopped
