---
- name: Install Redis
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: redis-server

- when:
    - redis.replication.sentinel
    - ansible_distribution == 'Ubuntu'
  block:

    - name: Install Redis Sentinel
      apt:
        name: redis-sentinel
      register: redis_sentinel_service_result

    - name: Stop Redis Sentinel
      when: redis_sentinel_service_result.changed
      service:
        name: redis-sentinel
        state: stopped
