---
- name: Update apt cache
  ansible.builtin.apt:
    cache_valid_time: 3600
  register: redis_update_apt_cache
  failed_when: >-
    redis_update_apt_cache.failed
    and not (
      ansible_check_mode
      and 'python3-apt must be installed to use check mode'
        in (redis_update_apt_cache.msg | default(''))
    )

- name: Install Redis
  notify: Start Redis
  ansible.builtin.apt:
    name: redis-server
  register: redis_install_apt_result
  failed_when: >-
    redis_install_apt_result.failed
    and not (
      ansible_check_mode
      and 'python3-apt must be installed to use check mode'
        in (redis_install_apt_result.msg | default(''))
    )

- when: redis.replication.sentinel
  block:
    - name: Install Redis Sentinel
      ansible.builtin.apt:
        name: redis-sentinel
      register: redis_install_sentinel_apt_result
      failed_when: >-
        redis_install_sentinel_apt_result.failed
        and not (
          ansible_check_mode
          and 'python3-apt must be installed to use check mode'
            in (redis_install_sentinel_apt_result.msg | default(''))
        )

    - name: Stop Redis Sentinel
      when: redis_install_sentinel_apt_result.changed
      ansible.builtin.service:
        name: "{{ redis.service.sentinel }}"
        state: stopped
