- name: Enable Redis service
  service:
    name: "{{ redis.service.server }}"
    enabled: yes

- name: Enable Redis Sentinel
  when:
    - ansible_system == 'Linux'
    - redis.replication.sentinel
  service:
    name: "{{ redis.service.sentinel }}"
    enabled: yes
