- name: Enable Redis service
  service:
    name: redis
    enabled: yes

- name: Enable Redis Sentinel
  when:
    - ansible_system == 'Linux'
    - redis.replication.sentinel
  service:
    name: redis-sentinel
    enabled: yes
